//
//  AttributedTextContentView.swift
//  DTCoreText
//
//  Created by Oliver Drobnik on 1/9/11.
//  Copyright 2011 Drobnik.com. All rights reserved.
//
//  Migrated to Swift, April 2026.
//

#if canImport(UIKit) && !os(watchOS)
import UIKit
import QuartzCore
import os.log

// MARK: - Notification

public extension Notification.Name {
	/// Posted when the content view finishes a layout pass.
	/// The `userInfo` dictionary contains an `"OptimalFrame"` key with an `NSValue` wrapping a `CGRect`.
	static let DTAttributedTextContentViewDidFinishLayout = Notification.Name(DTAttributedTextContentViewDidFinishLayoutNotification)
}

// MARK: - Relayout Mask

/// Option set controlling when the content view relayouts its text on bounds changes.
public struct DTAttributedTextContentViewRelayoutMask: OptionSet, @unchecked Sendable {
	public let rawValue: UInt

	public init(rawValue: UInt) {
		self.rawValue = rawValue
	}

	/// Never relayout automatically.
	public static let never = DTAttributedTextContentViewRelayoutMask([])

	/// Relayout when the width changes.
	public static let onWidthChanged = DTAttributedTextContentViewRelayoutMask(rawValue: 1 << 0)

	/// Relayout when the height changes.
	public static let onHeightChanged = DTAttributedTextContentViewRelayoutMask(rawValue: 1 << 1)
}

// MARK: - Delegate Protocol

/// Protocol to provide custom views for elements in an `AttributedTextContentView`.
/// Also receives notifications before/after drawing.
@objc public protocol DTAttributedTextContentViewDelegate: NSObjectProtocol {

	/// Called before a layout frame is drawn.
	@objc optional func attributedTextContentView(_ attributedTextContentView: DTAttributedTextContentView,
												  willDrawLayoutFrame layoutFrame: CoreTextLayoutFrame,
												  in context: CGContext)

	/// Called after a layout frame is drawn.
	@objc optional func attributedTextContentView(_ attributedTextContentView: DTAttributedTextContentView,
												  didDrawLayoutFrame layoutFrame: CoreTextLayoutFrame,
												  in context: CGContext)

	/// Called before a text block background is drawn. Return `true` to draw the default background fill.
	@objc optional func attributedTextContentView(_ attributedTextContentView: DTAttributedTextContentView,
												  shouldDrawBackgroundFor textBlock: TextBlock,
												  frame: CGRect,
												  context: CGContext,
												  forLayoutFrame layoutFrame: CoreTextLayoutFrame) -> Bool

	/// Provide a custom view for an attachment (e.g. an image view).
	@objc optional func attributedTextContentView(_ attributedTextContentView: DTAttributedTextContentView,
												  viewForAttachment attachment: TextAttachment,
												  frame: CGRect) -> UIView?

	/// Provide a custom view/button for a hyperlink.
	@objc optional func attributedTextContentView(_ attributedTextContentView: DTAttributedTextContentView,
												  viewForLink url: URL,
												  identifier: String,
												  frame: CGRect) -> UIView?

	/// Provide a generic custom view for an attributed string element.
	@objc optional func attributedTextContentView(_ attributedTextContentView: DTAttributedTextContentView,
												  viewForAttributedString string: NSAttributedString,
												  frame: CGRect) -> UIView?
}

// MARK: - Delegate Flags

/// Cached booleans for which delegate methods are implemented.
private struct DelegateFlags {
	var supportsCustomViewsForAttachments = false
	var supportsCustomViewsForLinks = false
	var supportsGenericCustomViews = false
	var supportsNotificationBeforeDrawing = false
	var supportsNotificationAfterDrawing = false
	var supportsNotificationBeforeTextBoxDrawing = false
}

// MARK: - Layer Class (Tiling)

/// Static storage for the global layer class override.
private var _layerClassForContentView: AnyClass?

// MARK: - AttributedTextContentView

/// Displays an attributed string generated by the HTML parser, with optional custom subviews for
/// images, links, and other attachments. By itself it does not scroll; for scrolling use `AttributedTextView`.
@objc(DTAttributedTextContentView)
open class AttributedTextContentView: UIView, AccessibilityViewProxyDelegate {

	// MARK: - Exposed Ivars (for subclasses)

	/// The attributed string being displayed.
	@objc open var _attributedString: NSAttributedString?

	/// The current layout frame.
	@objc open var _layoutFrame: CoreTextLayoutFrame?

	/// Edge insets around the text content.
	@objc open var _edgeInsets: UIEdgeInsets = .zero

	/// Maximum number of lines. 0 = unlimited.
	@objc open var _numberOfLines: Int = 0

	/// Line break mode used for truncation.
	@objc open var _lineBreakMode: NSLineBreakMode = .byWordWrapping

	/// String appended when truncation occurs.
	@objc open var _truncationString: NSAttributedString?

	/// Whether height is flexible (open-ended layout).
	@objc open var _flexibleHeight: Bool = false

	/// Index of custom views for attachments keyed by attachment hash.
	@objc public var customViewsForAttachmentsIndex: NSMutableDictionary?

	// MARK: - Private State

	private var _shouldAddFirstLineLeading = false
	private var _shouldDrawImages = true
	private var _shouldDrawLinks = true
	private var _shouldLayoutCustomSubviews = true
	private var _relayoutMask: DTAttributedTextContentViewRelayoutMask = .onWidthChanged

	private var _customViews = NSMutableSet()
	private var _customViewsForLinksIndex = NSMutableDictionary()

	private var _isTiling = false
	private var _layoutFrameHeightIsConstrainedByBounds = false

	private var _layouter: CoreTextLayouter?

	private var _layoutOffset: CGPoint = .zero
	private var _backgroundOffset: CGSize = .zero

	private var _delegateFlags = DelegateFlags()
	private weak var _delegate: (any DTAttributedTextContentViewDelegate)?

	/// Lock for synchronizing access to layouter/layoutFrame.
	private let _lock = NSLock()

	private var _accessibilityElements: [Any]?

	// MARK: - Tiling (Layer Class)

	/// Sets the layer class globally for new instances. Defaults to `CALayer`.
	@objc public class func setLayerClass(_ layerClass: AnyClass) {
		_layerClassForContentView = layerClass
	}

	override open class var layerClass: AnyClass {
		return _layerClassForContentView ?? CALayer.self
	}

	// MARK: - Init

	private func setup() {
		contentMode = .topLeft // avoid bitmap scaling on resize
		_shouldLayoutCustomSubviews = true
		_shouldAddFirstLineLeading = false
		_shouldDrawImages = true
		_shouldDrawLinks = true
		_layoutFrameHeightIsConstrainedByBounds = false
		_relayoutMask = .onWidthChanged

		if backgroundColor == nil {
			backgroundColor = UIColor.white
		}

		// Configure tile size if using CATiledLayer
		if let tiledLayer = layer as? CATiledLayer {
			let mainScreen = UIScreen.main
			let largerDimension = max(mainScreen.bounds.size.width, mainScreen.bounds.size.height)
			let scale = mainScreen.scale
			let tileSize = CGSize(width: largerDimension * scale, height: largerDimension * scale)
			tiledLayer.tileSize = tileSize
			_isTiling = true
		}
	}

	public override init(frame: CGRect) {
		super.init(frame: frame)
		setup()
	}

	public required init?(coder: NSCoder) {
		super.init(coder: coder)
	}

	open override func awakeFromNib() {
		super.awakeFromNib()
		setup()
	}

	deinit {
		if _isTiling {
			layer.contents = nil
			layer.delegate = nil
		}
		removeAllCustomViews()
	}

	// MARK: - Debug

	open override var debugDescription: String {
		guard let layoutFrame = _layoutFrame,
			  let fragment = layoutFrame.attributedStringFragment() else {
			return super.debugDescription
		}

		let visibleRange = layoutFrame.visibleStringRange()
		var extract = (fragment.string as NSString).substring(from: visibleRange.location)

		if extract.count > 10 {
			extract = String(extract.prefix(10))
		}

		return "<\(type(of: self)) \(self.frame) range:\(visibleRange) '\(extract)...'>"
	}

	// MARK: - Layout Subviews

	/// Removes invisible custom subviews and lays out subviews visible in the given rectangle.
	@objc open func layoutSubviews(in rect: CGRect) {
		// If called for a partial (non-infinite) rect, remove unneeded subviews first
		if !rect.isInfinite {
			removeSubviewsOutside(rect)
		}

		CATransaction.begin()
		CATransaction.setDisableActions(true)

		let theLayoutFrame = self.layoutFrame // synchronized

		guard let layoutString = theLayoutFrame?.attributedStringFragment() else {
			CATransaction.commit()
			return
		}

		let lines: [CoreTextLayoutLine]
		if rect.isInfinite {
			lines = (theLayoutFrame?.lines as? [CoreTextLayoutLine]) ?? []
		} else {
			lines = (theLayoutFrame?.linesVisible(in: rect) as? [CoreTextLayoutLine]) ?? []
		}

		// Hide all custom views
		for view in _customViews {
			(view as? UIView)?.isHidden = true
		}

		for oneLine in lines {
			var skipRunsBeforeLocation: Int = 0

			guard let glyphRuns = oneLine.glyphRuns as? [CoreTextGlyphRun] else { continue }

			for oneRun in glyphRuns {
				let runRange = oneRun.stringRange()
				var frameForSubview: CGRect = .zero

				guard runRange.location >= skipRunsBeforeLocation else { continue }

				// Check for link
				var effectiveRangeOfLink = runRange
				let attachment: TextAttachment? = oneRun.attachment
				var linkURL = oneRun.attributes[DTLinkAttribute] as? URL

				// Chain glyph runs for combined link buttons (skip attachments)
				if let linkURL_ = linkURL, attachment == nil {
					let glyphIndex = glyphRuns.firstIndex(of: oneRun) ?? 0

					for i in (glyphIndex + 1)..<glyphRuns.count {
						let followingRun = glyphRuns[i]
						let followingURL = followingRun.attributes[DTLinkAttribute] as? URL

						guard followingURL?.absoluteString == linkURL_.absoluteString else { break }
						guard followingRun.attachment == nil else { break }

						effectiveRangeOfLink = NSUnionRange(effectiveRangeOfLink, followingRun.stringRange())
					}

					frameForSubview = oneLine.frame(ofGlyphsWith: effectiveRangeOfLink)
					skipRunsBeforeLocation = NSMaxRange(effectiveRangeOfLink)
				} else {
					if let attachment {
						let ascender = attachment.ascentForLayout()
						let descender = attachment.descentForLayout()
						frameForSubview = CGRect(
							x: oneRun.frame.origin.x,
							y: oneLine.baselineOrigin.y - ascender,
							width: oneRun.frame.size.width,
							height: ascender + descender
						)
					} else {
						frameForSubview = oneRun.frame
					}
				}

				// Skip empty frames unless there's a lazily-loaded attachment
				if (frameForSubview.size.width <= 0 || frameForSubview.size.height <= 0) && attachment == nil {
					continue
				}

				var indexKey = NSNumber(value: runRange.location)

				// Offset layout if necessary
				if _layoutOffset != .zero {
					frameForSubview.origin.x += _layoutOffset.x
					frameForSubview.origin.y += _layoutOffset.y
				}

				// Round frame
				frameForSubview.origin.x = floor(frameForSubview.origin.x)
				frameForSubview.origin.y = ceil(frameForSubview.origin.y)
				frameForSubview.size.width = round(frameForSubview.size.width)
				frameForSubview.size.height = round(frameForSubview.size.height)

				if frameForSubview.minY > rect.maxY || frameForSubview.maxY < rect.minY {
					continue
				}

				// Handle attachments
				if let attachment {
					indexKey = NSNumber(value: attachment.hash)
					let existingAttachmentView = customViewsForAttachmentsIndex?.object(forKey: indexKey) as? UIView

					if let existingAttachmentView {
						existingAttachmentView.isHidden = false
						existingAttachmentView.frame = frameForSubview
						existingAttachmentView.alpha = 1
						existingAttachmentView.setNeedsLayout()
						existingAttachmentView.setNeedsDisplay()
						linkURL = nil // prevent link button on top of image
					} else {
						var newCustomAttachmentView: UIView?

						if attachment is DictationPlaceholderTextAttachment {
							newCustomAttachmentView = DictationPlaceholderView.placeholderView()
							newCustomAttachmentView?.frame = frameForSubview
						} else if _delegateFlags.supportsCustomViewsForAttachments {
							newCustomAttachmentView = _delegate?.attributedTextContentView?(self, viewForAttachment: attachment, frame: frameForSubview)
						} else if _delegateFlags.supportsGenericCustomViews {
							let string = layoutString.attributedSubstring(from: runRange).mutableCopy() as! NSMutableAttributedString
							string.addAttributes(Dictionary(uniqueKeysWithValues: (oneRun.attributes as? [String: Any] ?? [:]).map { (NSAttributedString.Key($0.key), $0.value) }), range: NSRange(location: 0, length: string.length))
							newCustomAttachmentView = _delegate?.attributedTextContentView?(self, viewForAttributedString: string, frame: frameForSubview)
						}

						if let newView = newCustomAttachmentView {
							newView.tag = indexKey.intValue
							addSubview(newView)
							_customViews.add(newView)
							if customViewsForAttachmentsIndex == nil {
								customViewsForAttachmentsIndex = NSMutableDictionary()
							}
							customViewsForAttachmentsIndex?.setObject(newView, forKey: indexKey)
							linkURL = nil // prevent link button on top of image
						}
					}
				}

				// Handle links
				if let linkURL, (_delegateFlags.supportsCustomViewsForLinks || _delegateFlags.supportsGenericCustomViews) {
					let existingLinkView = _customViewsForLinksIndex.object(forKey: indexKey) as? UIView

					// Ensure frame height is at least line height
					if frameForSubview.size.height < oneLine.frame.size.height {
						frameForSubview.origin.y = trunc(oneLine.frame.origin.y)
						frameForSubview.size.height = ceil(oneLine.frame.size.height)
					}

					if let existingLinkView {
						existingLinkView.frame = frameForSubview
						existingLinkView.isHidden = false
					} else {
						var newCustomLinkView: UIView?

						// Ensure frame height again (matching ObjC double-check)
						if frameForSubview.size.height < oneLine.frame.size.height {
							frameForSubview.origin.y = trunc(oneLine.frame.origin.y)
							frameForSubview.size.height = ceil(oneLine.frame.size.height)
						}

						if _delegateFlags.supportsCustomViewsForLinks {
							let attributes = layoutString.attributes(at: runRange.location, effectiveRange: nil)
							let guid = attributes[NSAttributedString.Key(DTGUIDAttribute)] as? String ?? ""
							newCustomLinkView = _delegate?.attributedTextContentView?(self, viewForLink: linkURL, identifier: guid, frame: frameForSubview)
						} else if _delegateFlags.supportsGenericCustomViews {
							let string = layoutString.attributedSubstring(from: runRange).mutableCopy() as! NSMutableAttributedString
							string.addAttributes(Dictionary(uniqueKeysWithValues: (oneRun.attributes as? [String: Any] ?? [:]).map { (NSAttributedString.Key($0.key), $0.value) }), range: NSRange(location: 0, length: string.length))
							newCustomLinkView = _delegate?.attributedTextContentView?(self, viewForAttributedString: string, frame: frameForSubview)
						}

						if let newView = newCustomLinkView {
							newView.tag = runRange.location
							addSubview(newView)
							_customViews.add(newView)
							_customViewsForLinksIndex.setObject(newView, forKey: indexKey)
						}
					}
				}
			}
		}

		CATransaction.commit()
	}

	open override func layoutSubviews() {
		if _shouldLayoutCustomSubviews {
			layoutSubviews(in: .infinite)
		}
		super.layoutSubviews()
	}

	// MARK: - Drawing

	open override func draw(_ layer: CALayer, in ctx: CGContext) {
		let rect = ctx.boundingBoxOfClipPath

		if _backgroundOffset.height != 0 || _backgroundOffset.width != 0 {
			ctx.setPatternPhase(_backgroundOffset)
		}

		if let bgColor = backgroundColor?.cgColor {
			ctx.setFillColor(bgColor)
		}
		ctx.fill(rect)

		// Offset layout if necessary
		if _layoutOffset != .zero {
			let transform = CGAffineTransform(translationX: _layoutOffset.x, y: _layoutOffset.y)
			ctx.concatenate(transform)
		}

		let theLayoutFrame = self.layoutFrame // synchronized

		// Construct drawing options
		var options = DTCoreTextLayoutFrameDrawingOptions.default.rawValue

		if !_shouldDrawImages {
			options |= DTCoreTextLayoutFrameDrawingOptions.omitAttachments.rawValue
		}

		if !_shouldDrawLinks {
			options |= DTCoreTextLayoutFrameDrawingOptions.omitLinks.rawValue
		}

		let drawingOptions = DTCoreTextLayoutFrameDrawingOptions(rawValue: options)

		if _delegateFlags.supportsNotificationBeforeDrawing {
			_delegate?.attributedTextContentView?(self, willDrawLayoutFrame: theLayoutFrame!, in: ctx)
		}

		theLayoutFrame?.draw(in: ctx, options: drawingOptions)

		if _delegateFlags.supportsNotificationAfterDrawing {
			_delegate?.attributedTextContentView?(self, didDrawLayoutFrame: theLayoutFrame!, in: ctx)
		}
	}

	open override func draw(_ rect: CGRect) {
		guard let context = UIGraphicsGetCurrentContext() else { return }
		self.layoutFrame?.draw(in: context, options: .default)
	}

	// MARK: - Relayout

	/// Discards the current layout frame and creates a new one based on the attributed string.
	@objc open func relayoutText() {
		let block: () -> Void = { [weak self] in
			guard let self else { return }
			guard _layoutFrame != nil, superview != nil else { return }

			// Need new layout frame; layouter can remain because the attributed string is probably the same
			self.layoutFrame = nil

			// Remove all links because they might have merged or split
			removeAllCustomViewsForLinks()

			if _attributedString != nil {
				// Triggers new layout
				let neededSize = intrinsicContentSize

				let optimalFrame = CGRect(x: frame.origin.x, y: frame.origin.y,
										  width: neededSize.width, height: neededSize.height)
				let userInfo: [String: Any] = ["OptimalFrame": NSValue(cgRect: optimalFrame)]

				NotificationCenter.default.post(
					name: .DTAttributedTextContentViewDidFinishLayout,
					object: self,
					userInfo: userInfo
				)
			}

			setNeedsLayout()
			setNeedsDisplay(bounds)
			invalidateIntrinsicContentSize()
		}

		if Thread.isMainThread { block() } else { DispatchQueue.main.async(execute: block) }
	}

	// MARK: - Custom View Management

	/// Removes all custom subviews for links.
	@objc open func removeAllCustomViewsForLinks() {
		guard let linkViews = _customViewsForLinksIndex.allValues as? [UIView] else { return }
		for view in linkViews {
			view.removeFromSuperview()
			_customViews.remove(view)
		}
		_customViewsForLinksIndex.removeAllObjects()
	}

	/// Removes all custom subviews (including links).
	@objc open func removeAllCustomViews() {
		let allViews = NSSet(set: _customViews)
		for case let view as UIView in allViews {
			view.removeFromSuperview()
			_customViews.remove(view)
		}
		customViewsForAttachmentsIndex?.removeAllObjects()
		_customViewsForLinksIndex.removeAllObjects()
	}

	/// Removes subviews whose frames lie entirely outside the given rect.
	private func removeSubviewsOutside(_ rect: CGRect) {
		let allViews = NSSet(set: _customViews)
		for case let view as UIView in allViews {
			if view.frame.minY > rect.maxY || view.frame.maxY < rect.minY {
				let indexKey = NSNumber(value: view.tag)
				view.removeFromSuperview()
				_customViews.remove(view)
				customViewsForAttachmentsIndex?.removeObject(forKey: indexKey)
				_customViewsForLinksIndex.removeObject(forKey: indexKey)
			}
		}
	}

	// MARK: - Sizing

	open override var bounds: CGRect {
		get { super.bounds }
		set {
			if super.bounds.size != newValue.size {
				_layoutFrame = nil
				invalidateIntrinsicContentSize()
			}
			super.bounds = newValue
		}
	}

	open override var intrinsicContentSize: CGSize {
		guard self.layoutFrame != nil else {
			return CGSize(width: UIView.noIntrinsicMetric, height: UIView.noIntrinsicMetric)
		}

		return CGSize(
			width: _layoutFrame!.frame.size.width + _edgeInsets.left + _edgeInsets.right,
			height: _layoutFrame!.frame.maxY + _edgeInsets.bottom
		)
	}

	open override func sizeThatFits(_ size: CGSize) -> CGSize {
		let neededSize = intrinsicContentSize
		if neededSize.width >= 0, neededSize.height >= 0 {
			return neededSize
		}
		return CGSize(width: _edgeInsets.left + _edgeInsets.right,
					  height: _edgeInsets.bottom + _edgeInsets.top)
	}

	/// Returns the rect for creating a layout frame constrained to the given width.
	private func frameForLayoutFrame(constrainedToWidth constrainWidth: CGFloat) -> CGRect {
		var width = constrainWidth
		if !width.isNormal {
			width = bounds.size.width
		}

		var adjustedBounds = bounds
		adjustedBounds.size.width = width
		var rect = adjustedBounds.inset(by: _edgeInsets)

		if rect.size.width <= 0 {
			return .zero
		}

		if _layoutFrameHeightIsConstrainedByBounds {
			if rect.size.height <= 0 {
				return .zero
			}
			// height already set from bounds
		} else {
			rect.size.height = CGFloat(CGFLOAT_HEIGHT_UNKNOWN)
		}

		return rect
	}

	/// Calculates the suggested frame size to fit the entire string constrained to a maximum width.
	@objc open func suggestedFrameSizeToFitEntireStringConstrainted(toWidth width: CGFloat) -> CGSize {
		let rect = frameForLayoutFrame(constrainedToWidth: width)
		guard let tmpLayoutFrame = self.layouter?.layoutFrame(with: rect, range: NSRange(location: 0, length: 0)) else {
			return .zero
		}

		tmpLayoutFrame.numberOfLines = _numberOfLines
		tmpLayoutFrame.lineBreakMode = _lineBreakMode
		tmpLayoutFrame.truncationString = _truncationString

		return CGSize(
			width: tmpLayoutFrame.frame.size.width + _edgeInsets.left + _edgeInsets.right,
			height: tmpLayoutFrame.frame.maxY + _edgeInsets.bottom
		)
	}

	// MARK: - Properties

	/// Edge insets around the text content.
	@objc open var edgeInsets: UIEdgeInsets {
		get { _edgeInsets }
		set {
			if newValue != _edgeInsets {
				_edgeInsets = newValue
				relayoutText()
				invalidateIntrinsicContentSize()
			}
		}
	}

	/// The attributed string to display.
	@objc open var attributedString: NSAttributedString? {
		get { _attributedString }
		set {
			guard _attributedString !== newValue else { return }

			// Keep the layouter, update string
			self.layouter?.attributedString = newValue

			_attributedString = newValue?.copy() as? NSAttributedString

			if _layoutFrame != nil {
				removeAllCustomViews()
				relayoutText()
			} else {
				setNeedsLayout()
				setNeedsDisplay(bounds)
			}

			invalidateIntrinsicContentSize()
		}
	}

	open override var frame: CGRect {
		get { super.frame }
		set {
			let oldFrame = super.frame
			super.frame = newValue

			guard _layoutFrame != nil else { return }

			var shouldRelayout = false

			if _relayoutMask.contains(.onHeightChanged), oldFrame.size.height != newValue.size.height {
				shouldRelayout = true
			}

			if _relayoutMask.contains(.onWidthChanged), oldFrame.size.width != newValue.size.width {
				shouldRelayout = true
			}

			if shouldRelayout {
				relayoutText()
			}

			if oldFrame.size.height < newValue.size.height {
				setNeedsDisplay(CGRect(x: 0, y: oldFrame.size.height,
									   width: bounds.size.width,
									   height: newValue.size.height - oldFrame.size.height))
			}
		}
	}

	/// Whether the receiver should add first-line leading.
	@objc open var shouldAddFirstLineLeading: Bool {
		get { _shouldAddFirstLineLeading }
		set {
			if _shouldAddFirstLineLeading != newValue {
				_shouldAddFirstLineLeading = newValue
				setNeedsDisplay()
				invalidateIntrinsicContentSize()
			}
		}
	}

	/// Whether the receiver should draw image attachments.
	@objc open var shouldDrawImages: Bool {
		get { _shouldDrawImages }
		set {
			if _shouldDrawImages != newValue {
				_shouldDrawImages = newValue
				setNeedsDisplay()
				invalidateIntrinsicContentSize()
			}
		}
	}

	/// Whether the receiver should draw hyperlinks.
	@objc open var shouldDrawLinks: Bool {
		get { _shouldDrawLinks }
		set {
			if _shouldDrawLinks != newValue {
				_shouldDrawLinks = newValue
				setNeedsDisplay()
				invalidateIntrinsicContentSize()
			}
		}
	}

	open override var backgroundColor: UIColor? {
		get { super.backgroundColor }
		set {
			super.backgroundColor = newValue
			if let color = newValue {
				isOpaque = color.cgColor.alpha >= 1.0
			} else {
				isOpaque = true
			}
		}
	}

	/// Whether the receiver calculates layout limited to the view bounds.
	@objc open var layoutFrameHeightIsConstrainedByBounds: Bool {
		get { _layoutFrameHeightIsConstrainedByBounds }
		set { _layoutFrameHeightIsConstrainedByBounds = newValue }
	}

	/// Whether the receiver should layout custom subviews in `layoutSubviews`.
	@objc open var shouldLayoutCustomSubviews: Bool {
		get { _shouldLayoutCustomSubviews }
		set { _shouldLayoutCustomSubviews = newValue }
	}

	/// The amount by which all content is offset for display and subview layouting.
	@objc open var layoutOffset: CGPoint {
		get { _layoutOffset }
		set { _layoutOffset = newValue }
	}

	/// The offset applied when drawing a pattern background color.
	@objc open var backgroundOffset: CGSize {
		get { _backgroundOffset }
		set { _backgroundOffset = newValue }
	}

	/// Bit mask that determines how the receiver relayouts when its bounds change.
	@objc open var relayoutMask: DTAttributedTextContentViewRelayoutMask {
		get { _relayoutMask }
		set { _relayoutMask = newValue }
	}

	/// Maximum number of lines to display. 0 = unlimited.
	@objc open var numberOfLines: Int {
		get { _numberOfLines }
		set { _numberOfLines = newValue }
	}

	/// The line break mode used for truncation.
	@objc open var lineBreakMode: NSLineBreakMode {
		get { _lineBreakMode }
		set { _lineBreakMode = newValue }
	}

	/// The string appended when truncation occurs.
	@objc open var truncationString: NSAttributedString? {
		get { _truncationString }
		set { _truncationString = newValue }
	}

	// MARK: - Layouter (synchronized)

	/// The layouter used for the receiver. Created automatically when needed.
	@objc open var layouter: CoreTextLayouter? {
		get {
			_lock.lock()
			defer { _lock.unlock() }

			if _layouter == nil, let string = _attributedString {
				_layouter = CoreTextLayouter(attributedString: string)
				_layouter?.shouldCacheLayoutFrames = true
			}
			return _layouter
		}
		set {
			_lock.lock()
			defer { _lock.unlock() }
			_layouter = newValue
		}
	}

	/// The layout frame used for the receiver. Created automatically when needed.
	@objc open var layoutFrame: CoreTextLayoutFrame? {
		get {
			_lock.lock()
			defer { _lock.unlock() }

			guard let theLayouter = layouter else { return _layoutFrame }

			if _layoutFrame == nil {
				var rect = bounds.inset(by: _edgeInsets)

				if rect.size.width <= 0 {
					return nil
				}

				if _layoutFrameHeightIsConstrainedByBounds {
					if rect.size.height <= 0 {
						return nil
					}
				} else {
					rect.size.height = CGFloat(CGFLOAT_HEIGHT_UNKNOWN)
				}

				_layoutFrame = theLayouter.layoutFrame(with: rect, range: NSRange(location: 0, length: 0))
				_layoutFrame?.numberOfLines = _numberOfLines
				_layoutFrame?.lineBreakMode = _lineBreakMode
				_layoutFrame?.truncationString = _truncationString

				// Post notification for initial layout
				let neededSize = CGSize(
					width: _layoutFrame!.frame.size.width + _edgeInsets.left + _edgeInsets.right,
					height: _layoutFrame!.frame.maxY + _edgeInsets.bottom
				)

				let optimalFrame = CGRect(x: frame.origin.x, y: frame.origin.y,
										  width: neededSize.width, height: neededSize.height)
				let userInfo: [String: Any] = ["OptimalFrame": NSValue(cgRect: optimalFrame)]

				NotificationCenter.default.post(
					name: .DTAttributedTextContentViewDidFinishLayout,
					object: self,
					userInfo: userInfo
				)

				// Set text block handler if delegate supports it
				if _delegateFlags.supportsNotificationBeforeTextBoxDrawing {
					_layoutFrame?.setTextBlockHandler { [weak self] textBlock, blockFrame, context, shouldDrawDefaultBackground in
						guard let self, let textBlock, let context else { return }
						let result = self._delegate?.attributedTextContentView?(
							self,
							shouldDrawBackgroundFor: textBlock,
							frame: blockFrame,
							context: context,
							forLayoutFrame: self._layoutFrame!
						) ?? true

						if let shouldDrawDefaultBackground {
							shouldDrawDefaultBackground.pointee = ObjCBool(result)
						}
					}
				}

				invalidateAccessibilityElements()
			}

			return _layoutFrame
		}
		set {
			_lock.lock()
			defer { _lock.unlock() }

			if _layoutFrame !== newValue {
				removeAllCustomViewsForLinks()

				if newValue != nil {
					setNeedsLayout()
					setNeedsDisplay(bounds)
				}
				_layoutFrame = newValue
				invalidateAccessibilityElements()
			}
		}
	}

	/// Delegate that provides custom behavior for the receiver.
	@objc open weak var delegate: (any DTAttributedTextContentViewDelegate)? {
		get { _delegate }
		set {
			_delegate = newValue

			_delegateFlags.supportsCustomViewsForAttachments = newValue?.responds(to: #selector(DTAttributedTextContentViewDelegate.attributedTextContentView(_:viewForAttachment:frame:))) ?? false
			_delegateFlags.supportsCustomViewsForLinks = newValue?.responds(to: #selector(DTAttributedTextContentViewDelegate.attributedTextContentView(_:viewForLink:identifier:frame:))) ?? false
			_delegateFlags.supportsGenericCustomViews = newValue?.responds(to: #selector(DTAttributedTextContentViewDelegate.attributedTextContentView(_:viewForAttributedString:frame:))) ?? false
			_delegateFlags.supportsNotificationBeforeDrawing = newValue?.responds(to: #selector(DTAttributedTextContentViewDelegate.attributedTextContentView(_:willDrawLayoutFrame:in:))) ?? false
			_delegateFlags.supportsNotificationAfterDrawing = newValue?.responds(to: #selector(DTAttributedTextContentViewDelegate.attributedTextContentView(_:didDrawLayoutFrame:in:))) ?? false
			_delegateFlags.supportsNotificationBeforeTextBoxDrawing = newValue?.responds(to: #selector(DTAttributedTextContentViewDelegate.attributedTextContentView(_:shouldDrawBackgroundFor:frame:context:forLayoutFrame:))) ?? false

			if !_delegateFlags.supportsCustomViewsForLinks && !_delegateFlags.supportsGenericCustomViews {
				removeAllCustomViewsForLinks()
			}

			// Don't draw images if delegate provides custom views
			if _delegateFlags.supportsGenericCustomViews || _delegateFlags.supportsCustomViewsForAttachments {
				_shouldDrawImages = false
			} else {
				_shouldDrawImages = true
			}
		}
	}

	// MARK: - Cursor (convenience methods delegating to layoutFrame)

	/// Determines the closest string index to a point in the receiver's frame.
	@objc open func closestCursorIndex(to point: CGPoint) -> Int {
		return self.layoutFrame?.closestCursorIndex(to: point) ?? NSNotFound
	}

	/// The rectangle to draw a caret at the given index.
	@objc open func cursorRect(atIndex index: Int) -> CGRect {
		return self.layoutFrame?.cursorRect(atIndex: index) ?? .zero
	}

	// MARK: - Drawing (Content Image)

	/// Creates an image from a part of the receiver's content.
	@objc open func contentImage(with contentBounds: CGRect, options: DTCoreTextLayoutFrameDrawingOptions) -> UIImage? {
		UIGraphicsBeginImageContextWithOptions(contentBounds.size, false, 0)

		guard let context = UIGraphicsGetCurrentContext() else {
			return nil
		}

		context.translateBy(x: -contentBounds.origin.x, y: -contentBounds.origin.y)
		self.layoutFrame?.draw(in: context, options: options)

		let image = UIGraphicsGetImageFromCurrentImageContext()
		UIGraphicsEndImageContext()

		return image
	}

	// MARK: - Accessibility

	private func invalidateAccessibilityElements() {
		_accessibilityElements = nil
	}

	open override var isAccessibilityElement: Bool {
		get { false }
		set { /* no-op */ }
	}

	open override var accessibilityElementCount: Int {
		return accessibilityElements?.count ?? 0
	}

	open override func accessibilityElement(at index: Int) -> Any? {
		guard let elements = accessibilityElements,
			  index >= 0, index < elements.count else {
			return nil
		}
		return elements[index]
	}

	open override func index(ofAccessibilityElement element: Any) -> Int {
		guard let elements = accessibilityElements else { return NSNotFound }
		let index = elements.firstIndex { obj in
			if let objNS = obj as? NSObject, let elemNS = element as? NSObject {
				return objNS.isEqual(elemNS)
			}
			return false
		}
		return index ?? NSNotFound
	}

	open override var accessibilityElements: [Any]? {
		get {
			if _accessibilityElements == nil {
				let generator = LayoutFrameAccessibilityElementGenerator()
				_accessibilityElements = generator.accessibilityElements(forLayoutFrame: self.layoutFrame, view: self) { [weak self] attachment in
					guard let self, let attachment else { return NSNull() }
					return AccessibilityViewProxy(textAttachment: attachment, delegate: self) as Any
				} as? [Any]
			}
			return _accessibilityElements
		}
		set {
			_accessibilityElements = newValue
		}
	}

	// MARK: - AccessibilityViewProxyDelegate

	@objc public func view(forTextAttachment textAttachment: TextAttachment, proxy: AccessibilityViewProxy) -> UIView {
		let indexKey = NSNumber(value: textAttachment.hash)
		return (customViewsForAttachmentsIndex?.object(forKey: indexKey) as? UIView) ?? UIView()
	}
}

#endif
